### PR TITLE
Add  Rmarkdown files to parsable-R hook

### LINKED ISSUE #319: Add hook for parseable Rmd
I use Rmd's a lot for my analysis, it would be nice to ensure that my Rmds are parseable (in addition to my R files)

Happy to contribute, it would be nice if you could point me in the right direction

I saw that there was an interesting R bloggers post here: https://www.r-bloggers.com/2021/09/pre-commit-hook-for-processing-readme-rmd/ but I'm not sure if that works well with the infrastructure you have set up here.

### PR DESCRIPTION
**Pull request by pwildenhain**
Closes #319

### CODE REVIEW

**Comment by pwildenhain** [comment]
> Also, you added your test to test/testthat/test-all.R. 

It's funny, I originally did add this to `test-hooks.R` but when I went back and read the `CONTRIBUTING.md` I added it to `test-all.R` 😂 

I'll make that change, and then make a few updates to `CONTRIBUTING.md` in a separate PR

**Comment by lorenzwalthert** [comment]
Also, all errors you see are unrelated.

**Comment by pwildenhain** [comment]
The `CONTRIBUTING.md` also mentions needing to add the hook script to the `inst/bin` directory -- is this still the case? I only made changes to `inst/hooks`

**Comment by lorenzwalthert** [comment]
That directory was renamed to `inst/hooks/exported`

**Comment by lorenzwalthert** [comment]
Thanks again @pwildenhain 🥳

**Pull request merged**
