### PR TITLE
Add read_only flag to run_test

### PR DESCRIPTION
**Pull request by TymekDev**
@lorenzwalthert please let me know if that's what you had in mind in https://github.com/lorenzwalthert/precommit/pull/511#pullrequestreview-1627271314

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Thanks for that contribution, looks good 👍 . Now the last step would be to set the flag for each test, ideally automatically. 
* A natural place to add a `read_only` marker would be in the `pre-commit-hooks.yaml` but I don't know if extending this specs would then give a run-time warning or error when running the hooks. 
* Another option is to define the hook order content from the vignette in plain R code, e.g. a tibble, and then use R to read that table and pretty print it in the vignette. 

Are you interested in investigating that further?

**Comment by TymekDev** [comment]
I read your ideas, and initially was on board to implement this. However, starting with #510 some of the write-hooks might get `--read-only` flag. Once that's the case we would need a combination of hook name and parsing `cmd_args` to check for said flag.

With that in mind I think it would make sense to leave this up to the person implementing test and set this argument retrospectively according to the current state.

What do you think?

**Comment by lorenzwalthert** [comment]
Sorry for the delay. Yeah maybe we can leave that for now, but at least for the existing tests that we have, it would make sense to apply the flag, no? You added the functionality, but if I understand your PR correctly, it is never set?

**Comment by lorenzwalthert** [comment]
Or did we agree to first implement the infra and then follow up? If yes, I think that's good for merging.

**Comment by lorenzwalthert** [comment]
Thanks again @TymekDev. 🥳

**Pull request merged**
