### PR TITLE
fix: missing namespace for diff_requires_run_roxygenize call in roxyg…

### PR DESCRIPTION
**Pull request by m-muecke**
…enize hook

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Uh… did your hook runs fail because of that? Can you provide some more context? Because in our CI, no error got thrown.

**Comment by m-muecke** [comment]
Yeah, just the roxygenise hook, with R version 4.3.1 and recommit v0.3.2.9021:
image

**Comment by lorenzwalthert** [comment]
Ah yes that code path is not tested in the integration test.

**Comment by lorenzwalthert** [comment]
Thanks. Will release a hook Update soon.

**Comment by lorenzwalthert** [comment]
Done, you should be able to get it with `> precommit::autoupdate()` or `$ pre-commit autopudate`.

**Pull request merged**
