### PR TITLE
Experiment with YAML formatter

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@lorenzwalthert I think this is working as expected, but because this PR itself contains changes to a YAML config file, which itself will be modified by this hook, there seems to be problems committing the changes.

Related to #448.

**Comment by IndrajeetPatil** [comment]
You can have a look at its formatting [here](https://github.com/IndrajeetPatil/statsExpressions/pull/208/files).

TBH, I am not sure if this is the hook to go with, since its formatting conflicts with VS Code's formatter.

**Comment by lorenzwalthert** [comment]
Plus it's not auto-fixing?

**Comment by IndrajeetPatil** [comment]
It did change the files initially. I think now it's not doing so because precommit is failing due to some other hooks failing.

VS code uses [prettier](https://github.com/prettier/prettier), and I see this mirror for it meant to be used with precommit: 

https://github.com/pre-commit/mirrors-prettier

**Comment by lorenzwalthert** [comment]
I don't see other hooks faililng in the latest run. Also, then I guess prettier is the better bet since it's so much more popular than the other repo and my initial favorite has not yet established a pre-commit hook.

**Comment by IndrajeetPatil** [comment]
Sounds good to me. Closing this.

**Pull request closed without merging**
