### PR TITLE
New hook: no-debug-statement (#290)

### PR DESCRIPTION
**Pull request by lukasfeick-sw**
Fixes https://github.com/lorenzwalthert/precommit/issues/290.

It took some time, but I now added a new hook similar to [no-browser-statement](https://github.com/lorenzwalthert/precommit/blob/master/inst/hooks/exported/no-browser-statement.R) which also checks for leftover `debug()` and `debugonce()` statements in the committed code.

I added the hook as a single new hook for now and [haven't yet "merged" it](https://github.com/lorenzwalthert/precommit/issues/290#issuecomment-881235626) with the existing `no-browser-statement` hook into a `no-debugging` hook as this would have required altering existing code. Happy to add this though if you think it makes sense.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Thanks @lukasfeick-sw, this PR looks great 👍. Thanks for taking the time to adhere to conventions already used. Two minor suggestions:

* Please add a news bullet in `NEWS.md` at the top of the current dev version to introduce your feature while adhering to the [tidyverse style conventions](https://style.tidyverse.org/news.html) for `NEWS.md`.
* Please add to the hook description in which version this was added, like `this hook was added in version 0.2.2.9012`. I got inspired by [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingClassifier.html?highlight=histgradient) and I think it's quite handy for users to know these API changes / additions.

To make sure CI passes, we need to probably rebase after #386 is merged.

**Comment by lukasfeick-sw** [comment]
Great, glad you like it! I now added a bullet to `NEWS.md` and added the version to the hook description as requested. Not entirely sure though whether to reference the issue number (#290) or the PR number (#385) in the `NEWS.md` bullet. I stuck with the original issue number now but feel free to update as you see fit.

**Comment by lorenzwalthert** [comment]
Great @lukasfeick-sw, thanks again. If you feel like contributing to any of the other open issues, feel free. I am happy to  provide guidance and code review.

**Comment by lorenzwalthert** [comment]
You should now be able to use the hook with the latest hook revision 0.2.2.9013.

**Pull request merged**
