### PR TITLE
Add a lintr flag for warning on pre-commit error

### PR DESCRIPTION
**Pull request by michaelquinn32**
This supports the option for notifying the user without blocking.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Thanks. To be honest, I think this goes against the spirit of pre-commit-hook. I mean technically, every hook needs such an argument then for consistency. But then what is the point of having these hooks if they are not enforced? Are there other hooks that work like this? I think the best way to go about that is to run the hook, see it fails and if the failure if it is a false positive, you can: 

- `git commit .. --no-verify` in a second attempt to skip *all* hooks.
- `SKIP=lintr git commit ...` to just skip the lintr hook.

Source: https://pre-commit.com/#temporarily-disabling-hooks

I do that from time to time with the styler hook for example.

**Comment by michaelquinn32** [comment]
At Google, we have pre-commit errors and warnings. The former are blocking, and the latter can be disabled. Distinguishing between these cases in R development will eventually be useful, but for now, being able to acknowledge code health messages is a good start.

We want developers to look at the lintr output, but it doesn't make sense to hard enforce it if we get into weird cases where lintr and styler disagree (as is the case right now with curly brackets). Nor does it make sense to have a developer manually suppress the results on every commit. After about three times, I'll just turn lintr off.

As for consistency, not all of the precommits do the same thing. Roxygenize and styler should always be on; DESCRIPTION checks are  a bit different, but I think fall under the same category.

On the other hand, lint warnings and spelling issues seem like a different category to me. I wouldn't want to tell a developer that they can't commit because our spell checker doesn't like the spelling of "Wickham."

**Comment by lorenzwalthert** [comment]
I see. But I can't see how I can make this a genuine warning. There is no reference in the pre-commit documentation. I think pre-commit only has pass or fail. Maybe open an issue in https://github.com/pre-commit/pre-commit? 

As far as lintr and spell check go, there is `nolint`, the lintr config file as well as `WORDLIST` for the spell checker which already gives a lot of controlled flexibility. 

Also, the warning you implemented does not show up when I test it with [pre-commit try-repo](https://pre-commit.com/#pre-commit-try-repo) unless you also set `verbose: true` in `.pre-commit-hooks.yaml`. The hook will be shown as passed plus some additional message. For me, this message is not informative and does not encourage the developer to check what exactly the issues are. Can we at least list / parse the problems here?

Screen Shot 2019-10-12 at 00 28 49

**Comment by michaelquinn32** [comment]
This looks doable:

R has return codes in quit():
https://stat.ethz.ch/R-manual/R-devel/library/base/html/quit.html

And pre-commit can have other statuses based on return code checks:
https://github.com/pre-commit/pre-commit/blob/bb108bf00e8a19bfb41a32afae7c4a9a58a56866/pre_commit/commands/run.py#L132

I'll open an issue.

**Comment by lorenzwalthert** [comment]
Well spotted. If we can make pre-commit issuing passed, warning or failed, I feel much better about implementing this PR 😀.

**Comment by michaelquinn32** [comment]
This is a configurable value.

```
id: lintr
args: [--warning_only]
vebose: True
```

The result is a hook `Passed` value, unfortunately, but the actual verbose results.

**Comment by lorenzwalthert** [comment]
Why do we have the lintr bot here? How did you add it? I have not configured this repo to work with the lintr bot. Also when you open an issue, can you link it here? I'd suggest to first wait and see if pre-commit want's to introduce the WARNING exit status. The maintainer is quite responsive.

**Comment by michaelquinn32** [comment]
Sorry, tbh, I have no idea why the lintr bot is here. I didn't intentionally add it to anything. The PR affects the readme's and the one bin/lintr file.

Also sorry for not linking in the issue:
https://github.com/pre-commit/pre-commit/issues/1167

It was closed as a duplicate. We could reopen it for explicit return codes, but otherwise the response said that we could set the option ourselves.

**Comment by lorenzwalthert** [comment]
So if I understand you correctly, it means that we have to put the following into the `.pre-commit-hooks.yaml` file: 

```
        entry: bash -c 'exe "$@" :(exec file here???) || true' --
```

Which means that users can't control if an error or a warning is returned?

**Comment by michaelquinn32** [comment]
Sorry that it's lost in the diffs, but you can get this by adding a "verbose" field to any configured check.

```
id: lintr
args: [--warning_only]
vebose: True
```

It doesn't give us proper warning return codes (with the correct colors in the passed/ failed output), but it is the correct behavior

**Comment by lorenzwalthert** [comment]
So are we not pursuing warning return codes in https://github.com/pre-commit/pre-commit?

**Comment by michaelquinn32** [comment]
Sorry for muddling things up.

1. With the config I listed above, running the pre-commits results in a `PASSED` code for lintr, but you still see all of the lintr messages.

2. Give then changes to the code and the aggressive autoformatting, I think it makes sense to drop this branch and implement the change starting at head. 

What do you think?

**Comment by lorenzwalthert** [comment]
Yes, if you make a fresh start, that would be most appreciated.

**Pull request closed without merging**
